.PHONY: help clean install quality quality-utils quality-main quality-notebooks test validate

.DEFAULT_GOAL := help

PY_MODULES = main.py utils
NOTEBOOKS  = notebooks

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, caches, and notebook checkpoints (cross-platform)
	python scripts/clean.py

install: ## install core + dev requirements (pycodestyle, nbqa)
	pip install -r requirements.txt
	pip install pycodestyle nbqa

quality-main: ## check PEP8 style on main.py
	pycodestyle main.py

quality-utils: ## check PEP8 style on utils/
	pycodestyle utils

quality-notebooks: ## check PEP8 style on notebooks/ (via nbqa)
	nbqa pycodestyle $(NOTEBOOKS)

quality: clean quality-main quality-utils ## run PEP8 checks on main.py, utils/, and notebooks/

test: clean ## run tests
	pytest tests

validate: quality test ## run quality checks and tests